var LOCALE_winsetup = [
    "",
    "Collecting information",
    "Installing Windows",
    "Installing Windows",
    "Not complete english translation...",
    "Вы найдёте его на задней стороне коробки с Windows или в сообщении, которое вы получили при покупке Windows.",
    "Product key look like: GCRJD-8NW9H-F2CDX-CCM8D-9D6T9",
    "Дефисы добавляются автоматически.",
    "License agreement",
    "agree",
    "Installing Windows",
    "Состояие",
    "Komputator neskolko raz perezagruzitsa.",
    "Copying Windows files ",
    "Extractin files ",
    "Installing features ",
    "Installing updates ",
    "Vse blin ",
    "(000%)",
    "Для продолжения требуется перезагрузка Windows",
    "Перезагрузка через 000 сек.",
    "Reboot now"
]